### ISSUE TITLE
Can't seem to get output

### ISSUE THREAD

**Issue by whatisgravity** [Depado/govue#1]
I tried running it then got an error that it was missing config.yml, so I created this file and added port: 3000. I started the program, but there is no output, expected gin output but got nothing. 

Any guidance available? I would love to contribute to this project and use it as the basis for my next project.

It does appear to be working though

**Comment by whatisgravity** [comment]
Getting things like:

```
{{ entry.attributes.title }}

{{ entry.attributes.markdown }}
```

Any idea why vue isn't working?

**Comment by whatisgravity** [comment]
It appears to be missing the vendor folder entirely.

**Comment by whatisgravity** [comment]
Can you provide the basic requirements in the vendor folder in the repo, then ignore the rest.

**Comment by depado** [comment]
Currently this project is just a test. I'll add further configuration instruction in the README.md.
