### ISSUE TITLE
Vendor folder

### ISSUE THREAD

**Issue by whatisgravity** [Depado/govue#2]
Can you please include the basic JS library requirements and the vendor folder in the repo. It would be easier for people to use the project, so they don't have to recreate the structure and find the libraries individually.

**Comment by depado** [comment]
Hi. There is a `package.json` file at the root of the project. Simply run `npm install` and you're good to go.

**Comment by whatisgravity** [comment]
I'm new to this stuff, thanks for the help.

**Comment by depado** [comment]
You're welcome. This step should create a `node_modules` at the root of the folder, containing everything you need.

**Comment by whatisgravity** [comment]
So I did that, then created a vendor folder and created symbolic links. It does not render correctly but still missing Jquery. Should I just go download this and create a folder or I'm I missing a step?

I will go ahead and document the steps and add them to read me and issue a pull request.

**Comment by whatisgravity** [comment]
Any guess why I would be getting a 404 on POST of /api/v1/entry/

The gin route appears to be there, not sure why this would be happening. I have not changed anything.

**Comment by depado** [comment]
There are no required steps like that.

```
go get github.com/Depado/govue
cd $GOPATH/src/Depado/govue
npm install
echo "port: 8080
  debug: true
  api_version: 1" > conf.yml
go build
./govue
```

I just gave that a try, it works out of the box.

**Comment by whatisgravity** [comment]
Ah, because I did not have a config file with the api version the router was not mounting to the right spot. Thanks for the additional details.

**Comment by depado** [comment]
You're welcome. I'll update the README.md file.

**Comment by depado** [comment]
Note that this is a work in progress, there are probably multiple bugs or things that won't work. It's not stable.

**Comment by whatisgravity** [comment]
I suspected as much, once I get my brain wrapped around it I'm sure I can help work out any. I may just write my own config and database connector code but it is nice to see a few examples and get them working to see how others have solved those problems.

**Comment by depado** [comment]
It was mainly just for testing purpose. I didn't really had a problem in the first place though. Note that the API calls and things like that follows (or attempt to follow) [this JSON API specification](http://jsonapi.org/format/). Kind of HATEOAS. That's quite the first time I'm writing an API with Go + Gin. Works great though.

**Comment by whatisgravity** [comment]
Do you have a method of getting the JQuery requirement or should that be included by default?

Are you interested in this project becoming a boilerplate to start with eventually? It seems like it could be a useful starting point eventually. 

I have written the start of 2 different just basic REST API's using gin and mgo and it worked well. I have never used bolt before so it will be nice to throw something together to test that portion out.

**Comment by whatisgravity** [comment]
Oh, I just needed to npm install jquery then symbolic link it to the right spot. I guess I will find out how to add that to the package.json file

**Comment by depado** [comment]
I think jQuery is a dependency of Bootstrap. So if you just `npm install` it should install jQuery in the right spot. I tested it yesterday and it worked out of the box. 

Sure, you can do whatever you want with that project. Although it's quite experimental, the code isn't really tidy as I struggled for the HATEOAS part. I think there are lots of improvements to do on that project. But suit yourself. I intend to continue developping it anyway, seeing how to add authentication, and stuff like that. (Both on the API end than on the front end)

I'm quite new to writing APIs as I told earlier. I also intend to create some tutorial on how to generate swagger documentation. But that will come in a second part.
